# Generated by Django 4.2.27 on 2026-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('system_a_value', models.TextField(blank=True, null=True)),
                ('system_b_value', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(db_index=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comparison_results',
                'ordering': ['record_id', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(db_index=True, max_length=50)),
                ('org_id', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=50)),
                ('location_id', models.CharField(blank=True, max_length=50, null=True)),
                ('event_date', models.CharField(blank=True, max_length=50, null=True)),
                ('category_code', models.CharField(blank=True, max_length=50, null=True)),
                ('actor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('base_value', models.CharField(blank=True, max_length=50, null=True)),
                ('adjustment', models.CharField(blank=True, max_length=50, null=True)),
                ('total_value', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'system_a_records',
            },
        ),
        migrations.CreateModel(
            name='SystemBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('record_ref', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('location_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_on', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'system_b_records',
            },
        ),
    ]
